modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"

[[mods]]
modId="fasterpath"
version="${file.jarVersion}"
displayName="Run faster on grass path blocks"
authors="DahakaMVl"
description='''
Run faster on grass path blocks.
'''